name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install Dependencies
      run: |
        pip freeze > requirements.txt
        pip install -r requirements.txt
      shell: bash
    - name: Pytest
      run: | 
        pwd
        pip install pytest
        pip install pytest-cov
        pytest
      shell: bash
