name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install Dependencies
      run: |
        pip freeze > requirements.txt
        pip install -r requirements.txt
      shell: pwsh
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@0.0.2
    - name: Run Pytest tests
      run: python pytest tests/
      shell: pwsh
