name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install Dependencies
      run: |
        pip freeze > requirements.txt
        pip install -r requirements.txt
      shell: bash
    - name: pwd
      run: | 
        pwd
        pip install pytest
      shell: bash
    
    - name: ls
      run: | 
        ls
      shell: bash
    
    - name: ls2
      run: | 
        cd ..
        ls
      shell: bash
    
    - name: pytest
      run: | 
        echo Python sucks!!!
        pytest
      shell: bash
